### ISSUE TITLE
Functional tests sometimes fail because a port is already in use.

### ISSUE THREAD

**Issue by ClifHouck** [rackerlabs/arsenal#88]
See the following:
```
======================================================================`
FAIL: arsenal.tests.functional.test_arsenal.TestArsenalStrategy.test_arsenal_caches_nodes_per_given_percentage_2
tags: worker-0
----------------------------------------------------------------------
Empty attachments:
  stderr

stdout: {{{
('2016-12-14T18:42:19+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.6.0 (/home/travis/build/rackerlabs/arsenal/.tox/py27/bin/python2.7 2.7.9) starting up.\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error] Traceback (most recent call last):\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/bin/twistd", line 11, in <module>\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     sys.exit(run())\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     app.run(runApp, ServerOptions)\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/application/app.py", line 648, in run\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     runApp(config)\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     _SomeApplicationRunner(config).run()\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/application/app.py", line 383, in run\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     self.postApplication()\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 248, in postApplication\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     self.startApplication(self.application)\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 435, in startApplication\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     service.IService(application).privilegedStartService()\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/application/service.py", line 278, in privilegedStartService\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     service.privilegedStartService()\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/application/service.py", line 278, in privilegedStartService\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     service.privilegedStartService()\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/twisted/application/internet.py", line 368, in privilegedStartService\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]     raisedNow[0].raiseException()\n', <type 'str'>)
('2016-12-14T18:42:19+0000 [stderr#error]   File "<string>", line 2, in raiseException\n', <type 'str'>)
("2016-12-14T18:42:19+0000 [stderr#error] twisted.internet.error.CannotListenError: Couldn't listen on any:3306: [Errno 98] Address already in use.\n", <type 'str'>)
('', <type 'str'>)
}}}

Traceback (most recent call last):
  File "arsenal/tests/functional/test_arsenal.py", line 119, in test_arsenal_caches_nodes_per_given_percentage_2
    before = self.get_unprovisioned_ironic_nodes()
  File "arsenal/tests/functional/base.py", line 262, in get_unprovisioned_ironic_nodes
    all_nodes = self.get_all_ironic_nodes()
  File "arsenal/tests/functional/base.py", line 247, in get_all_ironic_nodes
    nodes_list_response = requests.get(self.mimic_ironic_url + '/detail')
  File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/build/rackerlabs/arsenal/.tox/py27/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('_\x00\x00\x00\n',))
```

**Comment by ClifHouck** [comment]
I rekicked the failed job and it passed. Would be nice if functional tests retried picking a port a few times before failing.
